// Generated by gencpp from file path_follower/traj_plan.msg
// DO NOT EDIT!


#ifndef PATH_FOLLOWER_MESSAGE_TRAJ_PLAN_H
#define PATH_FOLLOWER_MESSAGE_TRAJ_PLAN_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace path_follower
{
template <class ContainerAllocator>
struct traj_plan_
{
  typedef traj_plan_<ContainerAllocator> Type;

  traj_plan_()
    : j(0)
    , i(0)
    , x(0.0)
    , y(0.0)
    , theta(0.0)
    , v(0.0)
    , rate_yaw(0.0)  {
    }
  traj_plan_(const ContainerAllocator& _alloc)
    : j(0)
    , i(0)
    , x(0.0)
    , y(0.0)
    , theta(0.0)
    , v(0.0)
    , rate_yaw(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _j_type;
  _j_type j;

   typedef int32_t _i_type;
  _i_type i;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _theta_type;
  _theta_type theta;

   typedef double _v_type;
  _v_type v;

   typedef double _rate_yaw_type;
  _rate_yaw_type rate_yaw;





  typedef boost::shared_ptr< ::path_follower::traj_plan_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::path_follower::traj_plan_<ContainerAllocator> const> ConstPtr;

}; // struct traj_plan_

typedef ::path_follower::traj_plan_<std::allocator<void> > traj_plan;

typedef boost::shared_ptr< ::path_follower::traj_plan > traj_planPtr;
typedef boost::shared_ptr< ::path_follower::traj_plan const> traj_planConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::path_follower::traj_plan_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::path_follower::traj_plan_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace path_follower

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'path_follower': ['/home/zhuoxu/RLRC/src/path_follower/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::path_follower::traj_plan_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_follower::traj_plan_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_follower::traj_plan_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_follower::traj_plan_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_follower::traj_plan_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_follower::traj_plan_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::path_follower::traj_plan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f8c2ada89420e3e8b85c22cafba5a2f5";
  }

  static const char* value(const ::path_follower::traj_plan_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf8c2ada89420e3e8ULL;
  static const uint64_t static_value2 = 0xb85c22cafba5a2f5ULL;
};

template<class ContainerAllocator>
struct DataType< ::path_follower::traj_plan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "path_follower/traj_plan";
  }

  static const char* value(const ::path_follower::traj_plan_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::path_follower::traj_plan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 j\n\
int32 i\n\
float64 x\n\
float64 y\n\
float64 theta\n\
float64 v\n\
float64 rate_yaw\n\
\n\
";
  }

  static const char* value(const ::path_follower::traj_plan_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::path_follower::traj_plan_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.j);
      stream.next(m.i);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
      stream.next(m.v);
      stream.next(m.rate_yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct traj_plan_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::path_follower::traj_plan_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::path_follower::traj_plan_<ContainerAllocator>& v)
  {
    s << indent << "j: ";
    Printer<int32_t>::stream(s, indent + "  ", v.j);
    s << indent << "i: ";
    Printer<int32_t>::stream(s, indent + "  ", v.i);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<double>::stream(s, indent + "  ", v.theta);
    s << indent << "v: ";
    Printer<double>::stream(s, indent + "  ", v.v);
    s << indent << "rate_yaw: ";
    Printer<double>::stream(s, indent + "  ", v.rate_yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATH_FOLLOWER_MESSAGE_TRAJ_PLAN_H
