classdef ControllerTarget < robotics.ros.Message
    %ControllerTarget MATLAB implementation of path_follower/ControllerTarget
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'path_follower/ControllerTarget' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '775bd3cf3d1e910e04e7d60f982bcda1' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        StdMsgsHeaderClass = robotics.ros.msg.internal.MessageFactory.getClassForType('std_msgs/Header') % Dispatch to MATLAB class for message type std_msgs/Header
    end
    
    properties (Dependent)
        Header
        TargetVelocity
        TargetSteeringAngle
        CrossTrackError
        HeadingError
        Timestamp
    end
    
    properties (Access = protected)
        Cache = struct('Header', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'CrossTrackError', 'Header', 'HeadingError', 'TargetSteeringAngle', 'TargetVelocity', 'Timestamp'} % List of non-constant message properties
        ROSPropertyList = {'cross_track_error', 'header', 'heading_error', 'target_steering_angle', 'target_velocity', 'timestamp'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = ControllerTarget(msg)
            %ControllerTarget Construct the message object ControllerTarget
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function header = get.Header(obj)
            %get.Header Get the value for property Header
            if isempty(obj.Cache.Header)
                obj.Cache.Header = feval(obj.StdMsgsHeaderClass, obj.JavaMessage.getHeader);
            end
            header = obj.Cache.Header;
        end
        
        function set.Header(obj, header)
            %set.Header Set the value for property Header
            validateattributes(header, {obj.StdMsgsHeaderClass}, {'nonempty', 'scalar'}, 'ControllerTarget', 'Header');
            
            obj.JavaMessage.setHeader(header.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Header)
                obj.Cache.Header.setJavaObject(header.getJavaObject);
            end
        end
        
        function targetvelocity = get.TargetVelocity(obj)
            %get.TargetVelocity Get the value for property TargetVelocity
            targetvelocity = double(obj.JavaMessage.getTargetVelocity);
        end
        
        function set.TargetVelocity(obj, targetvelocity)
            %set.TargetVelocity Set the value for property TargetVelocity
            validateattributes(targetvelocity, {'numeric'}, {'nonempty', 'scalar'}, 'ControllerTarget', 'TargetVelocity');
            
            obj.JavaMessage.setTargetVelocity(targetvelocity);
        end
        
        function targetsteeringangle = get.TargetSteeringAngle(obj)
            %get.TargetSteeringAngle Get the value for property TargetSteeringAngle
            targetsteeringangle = double(obj.JavaMessage.getTargetSteeringAngle);
        end
        
        function set.TargetSteeringAngle(obj, targetsteeringangle)
            %set.TargetSteeringAngle Set the value for property TargetSteeringAngle
            validateattributes(targetsteeringangle, {'numeric'}, {'nonempty', 'scalar'}, 'ControllerTarget', 'TargetSteeringAngle');
            
            obj.JavaMessage.setTargetSteeringAngle(targetsteeringangle);
        end
        
        function crosstrackerror = get.CrossTrackError(obj)
            %get.CrossTrackError Get the value for property CrossTrackError
            crosstrackerror = double(obj.JavaMessage.getCrossTrackError);
        end
        
        function set.CrossTrackError(obj, crosstrackerror)
            %set.CrossTrackError Set the value for property CrossTrackError
            validateattributes(crosstrackerror, {'numeric'}, {'nonempty', 'scalar'}, 'ControllerTarget', 'CrossTrackError');
            
            obj.JavaMessage.setCrossTrackError(crosstrackerror);
        end
        
        function headingerror = get.HeadingError(obj)
            %get.HeadingError Get the value for property HeadingError
            headingerror = double(obj.JavaMessage.getHeadingError);
        end
        
        function set.HeadingError(obj, headingerror)
            %set.HeadingError Set the value for property HeadingError
            validateattributes(headingerror, {'numeric'}, {'nonempty', 'scalar'}, 'ControllerTarget', 'HeadingError');
            
            obj.JavaMessage.setHeadingError(headingerror);
        end
        
        function timestamp = get.Timestamp(obj)
            %get.Timestamp Get the value for property Timestamp
            timestamp = double(obj.JavaMessage.getTimestamp);
        end
        
        function set.Timestamp(obj, timestamp)
            %set.Timestamp Set the value for property Timestamp
            validateattributes(timestamp, {'numeric'}, {'nonempty', 'scalar'}, 'ControllerTarget', 'Timestamp');
            
            obj.JavaMessage.setTimestamp(timestamp);
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Header = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.TargetVelocity = obj.TargetVelocity;
            cpObj.TargetSteeringAngle = obj.TargetSteeringAngle;
            cpObj.CrossTrackError = obj.CrossTrackError;
            cpObj.HeadingError = obj.HeadingError;
            cpObj.Timestamp = obj.Timestamp;
            
            % Recursively copy compound properties
            cpObj.Header = copy(obj.Header);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.TargetVelocity = strObj.TargetVelocity;
            obj.TargetSteeringAngle = strObj.TargetSteeringAngle;
            obj.CrossTrackError = strObj.CrossTrackError;
            obj.HeadingError = strObj.HeadingError;
            obj.Timestamp = strObj.Timestamp;
            obj.Header = feval([obj.StdMsgsHeaderClass '.loadobj'], strObj.Header);
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.TargetVelocity = obj.TargetVelocity;
            strObj.TargetSteeringAngle = obj.TargetSteeringAngle;
            strObj.CrossTrackError = obj.CrossTrackError;
            strObj.HeadingError = obj.HeadingError;
            strObj.Timestamp = obj.Timestamp;
            strObj.Header = saveobj(obj.Header);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.path_follower.ControllerTarget.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.path_follower.ControllerTarget;
            obj.reload(strObj);
        end
    end
end
