classdef state_Dynamic < robotics.ros.Message
    %state_Dynamic MATLAB implementation of path_follower/state_Dynamic
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'path_follower/state_Dynamic' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '02fc3873b6977b7d73d21690b9600a53' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        Vx
        Vy
        X
        Y
        Psi
        Wz
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Psi', 'Vx', 'Vy', 'Wz', 'X', 'Y'} % List of non-constant message properties
        ROSPropertyList = {'psi', 'vx', 'vy', 'wz', 'X', 'Y'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = state_Dynamic(msg)
            %state_Dynamic Construct the message object state_Dynamic
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function vx = get.Vx(obj)
            %get.Vx Get the value for property Vx
            vx = single(obj.JavaMessage.getVx);
        end
        
        function set.Vx(obj, vx)
            %set.Vx Set the value for property Vx
            validateattributes(vx, {'numeric'}, {'nonempty', 'scalar'}, 'state_Dynamic', 'Vx');
            
            obj.JavaMessage.setVx(vx);
        end
        
        function vy = get.Vy(obj)
            %get.Vy Get the value for property Vy
            vy = single(obj.JavaMessage.getVy);
        end
        
        function set.Vy(obj, vy)
            %set.Vy Set the value for property Vy
            validateattributes(vy, {'numeric'}, {'nonempty', 'scalar'}, 'state_Dynamic', 'Vy');
            
            obj.JavaMessage.setVy(vy);
        end
        
        function x = get.X(obj)
            %get.X Get the value for property X
            x = double(obj.JavaMessage.getX);
        end
        
        function set.X(obj, x)
            %set.X Set the value for property X
            validateattributes(x, {'numeric'}, {'nonempty', 'scalar'}, 'state_Dynamic', 'X');
            
            obj.JavaMessage.setX(x);
        end
        
        function y = get.Y(obj)
            %get.Y Get the value for property Y
            y = double(obj.JavaMessage.getY);
        end
        
        function set.Y(obj, y)
            %set.Y Set the value for property Y
            validateattributes(y, {'numeric'}, {'nonempty', 'scalar'}, 'state_Dynamic', 'Y');
            
            obj.JavaMessage.setY(y);
        end
        
        function psi = get.Psi(obj)
            %get.Psi Get the value for property Psi
            psi = single(obj.JavaMessage.getPsi);
        end
        
        function set.Psi(obj, psi)
            %set.Psi Set the value for property Psi
            validateattributes(psi, {'numeric'}, {'nonempty', 'scalar'}, 'state_Dynamic', 'Psi');
            
            obj.JavaMessage.setPsi(psi);
        end
        
        function wz = get.Wz(obj)
            %get.Wz Get the value for property Wz
            wz = single(obj.JavaMessage.getWz);
        end
        
        function set.Wz(obj, wz)
            %set.Wz Set the value for property Wz
            validateattributes(wz, {'numeric'}, {'nonempty', 'scalar'}, 'state_Dynamic', 'Wz');
            
            obj.JavaMessage.setWz(wz);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Vx = obj.Vx;
            cpObj.Vy = obj.Vy;
            cpObj.X = obj.X;
            cpObj.Y = obj.Y;
            cpObj.Psi = obj.Psi;
            cpObj.Wz = obj.Wz;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Vx = strObj.Vx;
            obj.Vy = strObj.Vy;
            obj.X = strObj.X;
            obj.Y = strObj.Y;
            obj.Psi = strObj.Psi;
            obj.Wz = strObj.Wz;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Vx = obj.Vx;
            strObj.Vy = obj.Vy;
            strObj.X = obj.X;
            strObj.Y = obj.Y;
            strObj.Psi = obj.Psi;
            strObj.Wz = obj.Wz;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.path_follower.state_Dynamic.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.path_follower.state_Dynamic;
            obj.reload(strObj);
        end
    end
end
