classdef traj_plan < robotics.ros.Message
    %traj_plan MATLAB implementation of path_follower/traj_plan
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'path_follower/traj_plan' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'f8c2ada89420e3e8b85c22cafba5a2f5' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        J
        I
        X
        Y
        Theta
        V
        RateYaw
    end
    
    properties (Constant, Hidden)
        PropertyList = {'I', 'J', 'RateYaw', 'Theta', 'V', 'X', 'Y'} % List of non-constant message properties
        ROSPropertyList = {'i', 'j', 'rate_yaw', 'theta', 'v', 'x', 'y'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = traj_plan(msg)
            %traj_plan Construct the message object traj_plan
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function j = get.J(obj)
            %get.J Get the value for property J
            j = int32(obj.JavaMessage.getJ);
        end
        
        function set.J(obj, j)
            %set.J Set the value for property J
            validateattributes(j, {'numeric'}, {'nonempty', 'scalar'}, 'traj_plan', 'J');
            
            obj.JavaMessage.setJ(j);
        end
        
        function i = get.I(obj)
            %get.I Get the value for property I
            i = int32(obj.JavaMessage.getI);
        end
        
        function set.I(obj, i)
            %set.I Set the value for property I
            validateattributes(i, {'numeric'}, {'nonempty', 'scalar'}, 'traj_plan', 'I');
            
            obj.JavaMessage.setI(i);
        end
        
        function x = get.X(obj)
            %get.X Get the value for property X
            x = double(obj.JavaMessage.getX);
        end
        
        function set.X(obj, x)
            %set.X Set the value for property X
            validateattributes(x, {'numeric'}, {'nonempty', 'scalar'}, 'traj_plan', 'X');
            
            obj.JavaMessage.setX(x);
        end
        
        function y = get.Y(obj)
            %get.Y Get the value for property Y
            y = double(obj.JavaMessage.getY);
        end
        
        function set.Y(obj, y)
            %set.Y Set the value for property Y
            validateattributes(y, {'numeric'}, {'nonempty', 'scalar'}, 'traj_plan', 'Y');
            
            obj.JavaMessage.setY(y);
        end
        
        function theta = get.Theta(obj)
            %get.Theta Get the value for property Theta
            theta = double(obj.JavaMessage.getTheta);
        end
        
        function set.Theta(obj, theta)
            %set.Theta Set the value for property Theta
            validateattributes(theta, {'numeric'}, {'nonempty', 'scalar'}, 'traj_plan', 'Theta');
            
            obj.JavaMessage.setTheta(theta);
        end
        
        function v = get.V(obj)
            %get.V Get the value for property V
            v = double(obj.JavaMessage.getV);
        end
        
        function set.V(obj, v)
            %set.V Set the value for property V
            validateattributes(v, {'numeric'}, {'nonempty', 'scalar'}, 'traj_plan', 'V');
            
            obj.JavaMessage.setV(v);
        end
        
        function rateyaw = get.RateYaw(obj)
            %get.RateYaw Get the value for property RateYaw
            rateyaw = double(obj.JavaMessage.getRateYaw);
        end
        
        function set.RateYaw(obj, rateyaw)
            %set.RateYaw Set the value for property RateYaw
            validateattributes(rateyaw, {'numeric'}, {'nonempty', 'scalar'}, 'traj_plan', 'RateYaw');
            
            obj.JavaMessage.setRateYaw(rateyaw);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.J = obj.J;
            cpObj.I = obj.I;
            cpObj.X = obj.X;
            cpObj.Y = obj.Y;
            cpObj.Theta = obj.Theta;
            cpObj.V = obj.V;
            cpObj.RateYaw = obj.RateYaw;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.J = strObj.J;
            obj.I = strObj.I;
            obj.X = strObj.X;
            obj.Y = strObj.Y;
            obj.Theta = strObj.Theta;
            obj.V = strObj.V;
            obj.RateYaw = strObj.RateYaw;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.J = obj.J;
            strObj.I = obj.I;
            strObj.X = obj.X;
            strObj.Y = obj.Y;
            strObj.Theta = obj.Theta;
            strObj.V = obj.V;
            strObj.RateYaw = obj.RateYaw;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.path_follower.traj_plan.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.path_follower.traj_plan;
            obj.reload(strObj);
        end
    end
end
