classdef Uout < robotics.ros.Message
    %Uout MATLAB implementation of path_follower/Uout
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'path_follower/Uout' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '73950a8bce4b9e8951518131a3cbe7f8' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        Acceleration
        Del
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Acceleration', 'Del'} % List of non-constant message properties
        ROSPropertyList = {'acceleration', 'del'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = Uout(msg)
            %Uout Construct the message object Uout
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function acceleration = get.Acceleration(obj)
            %get.Acceleration Get the value for property Acceleration
            acceleration = double(obj.JavaMessage.getAcceleration);
        end
        
        function set.Acceleration(obj, acceleration)
            %set.Acceleration Set the value for property Acceleration
            validateattributes(acceleration, {'numeric'}, {'nonempty', 'scalar'}, 'Uout', 'Acceleration');
            
            obj.JavaMessage.setAcceleration(acceleration);
        end
        
        function del = get.Del(obj)
            %get.Del Get the value for property Del
            del = double(obj.JavaMessage.getDel);
        end
        
        function set.Del(obj, del)
            %set.Del Set the value for property Del
            validateattributes(del, {'numeric'}, {'nonempty', 'scalar'}, 'Uout', 'Del');
            
            obj.JavaMessage.setDel(del);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Acceleration = obj.Acceleration;
            cpObj.Del = obj.Del;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Acceleration = strObj.Acceleration;
            obj.Del = strObj.Del;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Acceleration = obj.Acceleration;
            strObj.Del = obj.Del;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.path_follower.Uout.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.path_follower.Uout;
            obj.reload(strObj);
        end
    end
end
