# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from path_follower/Actuator.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class Actuator(genpy.Message):
  _md5sum = "8164b580b4ff14b976d32e45c6c9f9d9"
  _type = "path_follower/Actuator"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
uint8 direction
uint8 steering_mode
float64 steering_value     # depending on steering_mode this is either angle or torque
float64 brake_pressure
float64 throttle_fraction
float64 timestamp

  # for direction
uint8 DIRECTION_FORWARD = 0
uint8 DIRECTION_REVERSE = 1

  # for steering mode
uint8 ANGLE_CONTROL = 0
uint8 TORQUE_CONTROL = 1



================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id
"""
  # Pseudo-constants
  DIRECTION_FORWARD = 0
  DIRECTION_REVERSE = 1
  ANGLE_CONTROL = 0
  TORQUE_CONTROL = 1

  __slots__ = ['header','direction','steering_mode','steering_value','brake_pressure','throttle_fraction','timestamp']
  _slot_types = ['std_msgs/Header','uint8','uint8','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,direction,steering_mode,steering_value,brake_pressure,throttle_fraction,timestamp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Actuator, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.direction is None:
        self.direction = 0
      if self.steering_mode is None:
        self.steering_mode = 0
      if self.steering_value is None:
        self.steering_value = 0.
      if self.brake_pressure is None:
        self.brake_pressure = 0.
      if self.throttle_fraction is None:
        self.throttle_fraction = 0.
      if self.timestamp is None:
        self.timestamp = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.direction = 0
      self.steering_mode = 0
      self.steering_value = 0.
      self.brake_pressure = 0.
      self.throttle_fraction = 0.
      self.timestamp = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2B4d().pack(_x.direction, _x.steering_mode, _x.steering_value, _x.brake_pressure, _x.throttle_fraction, _x.timestamp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 34
      (_x.direction, _x.steering_mode, _x.steering_value, _x.brake_pressure, _x.throttle_fraction, _x.timestamp,) = _get_struct_2B4d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2B4d().pack(_x.direction, _x.steering_mode, _x.steering_value, _x.brake_pressure, _x.throttle_fraction, _x.timestamp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 34
      (_x.direction, _x.steering_mode, _x.steering_value, _x.brake_pressure, _x.throttle_fraction, _x.timestamp,) = _get_struct_2B4d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B4d = None
def _get_struct_2B4d():
    global _struct_2B4d
    if _struct_2B4d is None:
        _struct_2B4d = struct.Struct("<2B4d")
    return _struct_2B4d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
