# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from path_follower/state_Dynamic.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class state_Dynamic(genpy.Message):
  _md5sum = "02fc3873b6977b7d73d21690b9600a53"
  _type = "path_follower/state_Dynamic"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 vx      # m/s
float32 vy      # m/s
float64 X       # m
float64 Y       # m
float32 psi     # rad
float32 wz      # rad/s

"""
  __slots__ = ['vx','vy','X','Y','psi','wz']
  _slot_types = ['float32','float32','float64','float64','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       vx,vy,X,Y,psi,wz

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(state_Dynamic, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.vx is None:
        self.vx = 0.
      if self.vy is None:
        self.vy = 0.
      if self.X is None:
        self.X = 0.
      if self.Y is None:
        self.Y = 0.
      if self.psi is None:
        self.psi = 0.
      if self.wz is None:
        self.wz = 0.
    else:
      self.vx = 0.
      self.vy = 0.
      self.X = 0.
      self.Y = 0.
      self.psi = 0.
      self.wz = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2f2d2f().pack(_x.vx, _x.vy, _x.X, _x.Y, _x.psi, _x.wz))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.vx, _x.vy, _x.X, _x.Y, _x.psi, _x.wz,) = _get_struct_2f2d2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2f2d2f().pack(_x.vx, _x.vy, _x.X, _x.Y, _x.psi, _x.wz))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.vx, _x.vy, _x.X, _x.Y, _x.psi, _x.wz,) = _get_struct_2f2d2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2f2d2f = None
def _get_struct_2f2d2f():
    global _struct_2f2d2f
    if _struct_2f2d2f is None:
        _struct_2f2d2f = struct.Struct("<2f2d2f")
    return _struct_2f2d2f
