# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from path_follower/traj_plan.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class traj_plan(genpy.Message):
  _md5sum = "f8c2ada89420e3e8b85c22cafba5a2f5"
  _type = "path_follower/traj_plan"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 j
int32 i
float64 x
float64 y
float64 theta
float64 v
float64 rate_yaw

"""
  __slots__ = ['j','i','x','y','theta','v','rate_yaw']
  _slot_types = ['int32','int32','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       j,i,x,y,theta,v,rate_yaw

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(traj_plan, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.j is None:
        self.j = 0
      if self.i is None:
        self.i = 0
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.theta is None:
        self.theta = 0.
      if self.v is None:
        self.v = 0.
      if self.rate_yaw is None:
        self.rate_yaw = 0.
    else:
      self.j = 0
      self.i = 0
      self.x = 0.
      self.y = 0.
      self.theta = 0.
      self.v = 0.
      self.rate_yaw = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2i5d().pack(_x.j, _x.i, _x.x, _x.y, _x.theta, _x.v, _x.rate_yaw))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.j, _x.i, _x.x, _x.y, _x.theta, _x.v, _x.rate_yaw,) = _get_struct_2i5d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2i5d().pack(_x.j, _x.i, _x.x, _x.y, _x.theta, _x.v, _x.rate_yaw))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.j, _x.i, _x.x, _x.y, _x.theta, _x.v, _x.rate_yaw,) = _get_struct_2i5d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2i5d = None
def _get_struct_2i5d():
    global _struct_2i5d
    if _struct_2i5d is None:
        _struct_2i5d = struct.Struct("<2i5d")
    return _struct_2i5d
