# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from path_follower/TrajectoryPoint2D.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class TrajectoryPoint2D(genpy.Message):
  _md5sum = "63ab900fed4c2c35d54c1d98c787e72b"
  _type = "path_follower/TrajectoryPoint2D"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """#Header header  not sent directly
float64 t
float64 x
float64 y
float64 theta
float64 kappa
float64 kappa_dot
float64 v
float64 a
float64 jerk
float64 delta_theta     # heading misalignment with center line
float64 d               # offset to center line
float64 a_lat           # lateral (to traj not to center line!) acceleration
"""
  __slots__ = ['t','x','y','theta','kappa','kappa_dot','v','a','jerk','delta_theta','d','a_lat']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       t,x,y,theta,kappa,kappa_dot,v,a,jerk,delta_theta,d,a_lat

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TrajectoryPoint2D, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.t is None:
        self.t = 0.
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.theta is None:
        self.theta = 0.
      if self.kappa is None:
        self.kappa = 0.
      if self.kappa_dot is None:
        self.kappa_dot = 0.
      if self.v is None:
        self.v = 0.
      if self.a is None:
        self.a = 0.
      if self.jerk is None:
        self.jerk = 0.
      if self.delta_theta is None:
        self.delta_theta = 0.
      if self.d is None:
        self.d = 0.
      if self.a_lat is None:
        self.a_lat = 0.
    else:
      self.t = 0.
      self.x = 0.
      self.y = 0.
      self.theta = 0.
      self.kappa = 0.
      self.kappa_dot = 0.
      self.v = 0.
      self.a = 0.
      self.jerk = 0.
      self.delta_theta = 0.
      self.d = 0.
      self.a_lat = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_12d().pack(_x.t, _x.x, _x.y, _x.theta, _x.kappa, _x.kappa_dot, _x.v, _x.a, _x.jerk, _x.delta_theta, _x.d, _x.a_lat))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 96
      (_x.t, _x.x, _x.y, _x.theta, _x.kappa, _x.kappa_dot, _x.v, _x.a, _x.jerk, _x.delta_theta, _x.d, _x.a_lat,) = _get_struct_12d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_12d().pack(_x.t, _x.x, _x.y, _x.theta, _x.kappa, _x.kappa_dot, _x.v, _x.a, _x.jerk, _x.delta_theta, _x.d, _x.a_lat))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 96
      (_x.t, _x.x, _x.y, _x.theta, _x.kappa, _x.kappa_dot, _x.v, _x.a, _x.jerk, _x.delta_theta, _x.d, _x.a_lat,) = _get_struct_12d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_12d = None
def _get_struct_12d():
    global _struct_12d
    if _struct_12d is None:
        _struct_12d = struct.Struct("<12d")
    return _struct_12d
