# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from path_follower/waypoint.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import path_follower.msg
import std_msgs.msg

class waypoint(genpy.Message):
  _md5sum = "b21d34b30e27765edf6b1596d61c4d30"
  _type = "path_follower/waypoint"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Pose2D pose
geometry_msgs/TwistStamped twist
dtlane dtlane
int32 change_flag

================================================================================
MSG: geometry_msgs/Pose2D
# This expresses a position and orientation on a 2D manifold.

float64 x
float64 y
float64 theta
================================================================================
MSG: geometry_msgs/TwistStamped
# A twist with reference coordinate frame and timestamp
Header header
Twist twist

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Twist
# This expresses velocity in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: path_follower/dtlane
float64 dist
float64 dir
float64 apara
float64 r
float64 slope
float64 cant
float64 lw
float64 rw
"""
  __slots__ = ['pose','twist','dtlane','change_flag']
  _slot_types = ['geometry_msgs/Pose2D','geometry_msgs/TwistStamped','path_follower/dtlane','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pose,twist,dtlane,change_flag

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(waypoint, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.pose is None:
        self.pose = geometry_msgs.msg.Pose2D()
      if self.twist is None:
        self.twist = geometry_msgs.msg.TwistStamped()
      if self.dtlane is None:
        self.dtlane = path_follower.msg.dtlane()
      if self.change_flag is None:
        self.change_flag = 0
    else:
      self.pose = geometry_msgs.msg.Pose2D()
      self.twist = geometry_msgs.msg.TwistStamped()
      self.dtlane = path_follower.msg.dtlane()
      self.change_flag = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3d3I().pack(_x.pose.x, _x.pose.y, _x.pose.theta, _x.twist.header.seq, _x.twist.header.stamp.secs, _x.twist.header.stamp.nsecs))
      _x = self.twist.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_14di().pack(_x.twist.twist.linear.x, _x.twist.twist.linear.y, _x.twist.twist.linear.z, _x.twist.twist.angular.x, _x.twist.twist.angular.y, _x.twist.twist.angular.z, _x.dtlane.dist, _x.dtlane.dir, _x.dtlane.apara, _x.dtlane.r, _x.dtlane.slope, _x.dtlane.cant, _x.dtlane.lw, _x.dtlane.rw, _x.change_flag))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.pose is None:
        self.pose = geometry_msgs.msg.Pose2D()
      if self.twist is None:
        self.twist = geometry_msgs.msg.TwistStamped()
      if self.dtlane is None:
        self.dtlane = path_follower.msg.dtlane()
      end = 0
      _x = self
      start = end
      end += 36
      (_x.pose.x, _x.pose.y, _x.pose.theta, _x.twist.header.seq, _x.twist.header.stamp.secs, _x.twist.header.stamp.nsecs,) = _get_struct_3d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.twist.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.twist.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 116
      (_x.twist.twist.linear.x, _x.twist.twist.linear.y, _x.twist.twist.linear.z, _x.twist.twist.angular.x, _x.twist.twist.angular.y, _x.twist.twist.angular.z, _x.dtlane.dist, _x.dtlane.dir, _x.dtlane.apara, _x.dtlane.r, _x.dtlane.slope, _x.dtlane.cant, _x.dtlane.lw, _x.dtlane.rw, _x.change_flag,) = _get_struct_14di().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3d3I().pack(_x.pose.x, _x.pose.y, _x.pose.theta, _x.twist.header.seq, _x.twist.header.stamp.secs, _x.twist.header.stamp.nsecs))
      _x = self.twist.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_14di().pack(_x.twist.twist.linear.x, _x.twist.twist.linear.y, _x.twist.twist.linear.z, _x.twist.twist.angular.x, _x.twist.twist.angular.y, _x.twist.twist.angular.z, _x.dtlane.dist, _x.dtlane.dir, _x.dtlane.apara, _x.dtlane.r, _x.dtlane.slope, _x.dtlane.cant, _x.dtlane.lw, _x.dtlane.rw, _x.change_flag))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.pose is None:
        self.pose = geometry_msgs.msg.Pose2D()
      if self.twist is None:
        self.twist = geometry_msgs.msg.TwistStamped()
      if self.dtlane is None:
        self.dtlane = path_follower.msg.dtlane()
      end = 0
      _x = self
      start = end
      end += 36
      (_x.pose.x, _x.pose.y, _x.pose.theta, _x.twist.header.seq, _x.twist.header.stamp.secs, _x.twist.header.stamp.nsecs,) = _get_struct_3d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.twist.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.twist.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 116
      (_x.twist.twist.linear.x, _x.twist.twist.linear.y, _x.twist.twist.linear.z, _x.twist.twist.angular.x, _x.twist.twist.angular.y, _x.twist.twist.angular.z, _x.dtlane.dist, _x.dtlane.dir, _x.dtlane.apara, _x.dtlane.r, _x.dtlane.slope, _x.dtlane.cant, _x.dtlane.lw, _x.dtlane.rw, _x.change_flag,) = _get_struct_14di().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3d3I = None
def _get_struct_3d3I():
    global _struct_3d3I
    if _struct_3d3I is None:
        _struct_3d3I = struct.Struct("<3d3I")
    return _struct_3d3I
_struct_14di = None
def _get_struct_14di():
    global _struct_14di
    if _struct_14di is None:
        _struct_14di = struct.Struct("<14di")
    return _struct_14di
